version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    ECR_REPO: 615299760779.dkr.ecr.us-east-1.amazonaws.com/above20mb-file-vectorization
    IMAGE_TAG: latest

phases:

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$(echo "$ECR_REPO" | cut -d/ -f1)"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t above20mb-file-vectorization:$IMAGE_TAG .
      - docker tag above20mb-file-vectorization:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPO:$IMAGE_TAG
      - echo "Docker image pushed successfully."